name: Build Firmware

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get ARM toolchain
      run: |
        wget https://developer.arm.com/-/media/Files/downloads/gnu/14.2.rel1/binrel/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi.tar.xz
        tar xf arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi.tar.xz -C "$HOME"

    - name: Setup path
      run: echo "$HOME/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi/bin" >> $GITHUB_PATH

    - name: Build Dyno
      run: cd projects && cd dyno && make

    - name: Build Etherbotix
      run: cd projects && cd etherbotix && make

    - name: Build Etherbotix Bootloader
      run: cd projects && cd etherbotix && cd bootloader && make

    - name: Build Tablebot
      run: cd projects && cd tablebot && make

